# Generated by Django 2.0 on 2018-12-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='open_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
